baseURL = "https://example.org/"
title = "PLEASE"
theme = ["doks"]

enableRobotsTXT = true

outputs.home = ["html", "llms"]
outputs.page = ["html"]
outputs.section = ["html", "rss"]

[markup]
  [markup.highlight]
    noClasses = false
  [markup.goldmark.renderer]
    unsafe = true

[[menu.main]]
  identifier = "docs"
  name = "Documentation"
  pageRef = "/docs/commands/please-commit"
  weight = 1

[[menu.main]]
  identifier = "download"
  name = "Download"
  pageRef = "/docs/getting-started/installation"
  weight = 2

[[menu.main]]
  name = "Search"
  weight = 2
  [menu.main.params]
    type = "search"

[[menu.main]]
  name = "GitHub"
  weight = 3
  url = "https://github.com/HylithLabs/please/"
  [menu.main.params]
    icon = "github"

[params]
  description = "Documentation for please, an AI native git command line tool."

  externalLinkDecoration = true

  [params.navbar]
    displayTitle = true
    displayLogo = false
    width = "wide"

  [params.theme]
    default = "system"
    displayToggle = true

  [params.footer]
    enable = true
    displayCopyright = true
    displayPoweredBy = true
    width = "normal"

  displayUpdatedDate = true
  dateFormat = "January 2, 2006"

  [params.search]
    enable = true
    type = "flexsearch"
    [params.search.flexsearch]
      index = "content"
      tokenize = "forward"

  [params.highlight.copy]
    enable = true
    display = "hover"

  [params.page]
    width = "normal"

  [params.toc]
    displayTags = false

[seo.favicons]
  icon = "favicon.ico"
